babel.es2015.config.js
packages/analyticsConnector/package.json
packages/analyticsConnector/rollup.config.js
packages/browser/package.json
packages/browser/rollup.config.js

fixes https://github.com/amplitude/experiment-js-client/issues/37
* keep existing umd build untouched to not break existing usages
* add `{ "module": "dist/<package>.esm.js" }` with `es5` syntax and es modules
* add `{ "es2015": "dist/<package>.es2015.js" }` with `es2015` syntax and es modules
So you can reuse modules from amplitude (instead of e.g. having `@amplitude/ua-parser-js` 3 times in your build) and if you don't care about IE11, can use the smaller es2015 syntax.

build: add esm and es2015 builds

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/stubClient.ts
packages/experiment-browser/src/types/client.ts
packages/experiment-browser/test/client.test.ts

Add functionality for manipulating the flag config cache

feat: add clear method to clear flag configs

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/test/client.test.ts

Subset flags update introduced bug where disabled flags were not removed from storage. In practice the storage was strictly additive, unless specific flag keys were sent in the request.

fix: clear cache if no flag keys so disabled flags are cleared

---

examples/html-app/amplitude-integration/index.html
examples/html-app/basic/index.html
examples/react-app/amplitude-integration/src/index.tsx
examples/react-app/basic/src/index.tsx
packages/experiment-browser/src/factory.ts
packages/experiment-browser/src/integration/default.ts
packages/experiment-browser/test/defaultUserProvider.test.ts

Fix using usparser to gather device info for fetch request when using amplitude analytics integration

fix: device tracking with amplitude integration

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/integration/default.ts

Fix regression in device info fix. Unwrap the default user provider to access connector user provider.

fix: unwrap default user provider before connector

---

packages/analytics-connector/package.json

Given that the ua-parser package does not live in this mono-repo, its releases are not in sync. The exact version used here leads to installing 2 different versions of the ua-parser as part of the dependencies of the analytics-browser package, and both are part of the bundle, increasing the bundle size.
Closes https://github.com/amplitude/Amplitude-TypeScript/issues/373

fix(deps): Use a range constraint for the ua-parser package

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/types/exposure.ts
packages/experiment-browser/src/types/variant.ts
packages/experiment-browser/test/client.test.ts

Add experiment key to variant and exposure event

feat: support expeirment key on variant and exposure event

---

packages/experiment-browser/rollup.config.js

Exclude @amplitude/ua-parser-js from bundle. This dependency will be installed by consumer and will be used by this package.
cc @stof 

fix: remove duplicated user agent parser from build

---

packages/analytics-connector/src/identityStore.ts
packages/analytics-connector/test/identityStore.test.ts

Add ability to set optOut in the analytics connector identity store

feat(analytics-connector): add support for setting opt out in identity store

---

packages/experiment-browser/src/experimentClient.ts

* Call `get()` for accessing the variant rather than `getAll()[key]`
* Check if there is a legacy exposure tracker before adding context to the user

fix: optimize variant cache access, legacy exposure

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/storage/cache.ts
packages/experiment-browser/src/storage/local-storage.ts
packages/experiment-browser/src/types/storage.ts
packages/experiment-browser/test/util/mock.ts

Storage functions were needlessly async

fix: make storage synchronous

---

packages/experiment-browser/src/config.ts
packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/test/client.test.ts

call fetch on start by default

fix: call fetch on start by default

---

packages/experiment-browser/src/experimentClient.ts

Remove undefined localStorage log message.

fix: remove undefined localStorage log message

---

packages/experiment-browser/src/config.ts
packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/test/client.test.ts

bootstrap initial local evaluation flags

feat: bootstrap initial local evaluation flags

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/util.ts
packages/experiment-tag/test/experiment.test.ts
packages/experiment-tag/test/util.test.ts

Add support for search param sharing in split url experiments

chore: Support search param sharing for split url experiments

---

packages/experiment-browser/src/experimentClient.ts

fix `variant()` debug log which was logging "variant is undefined" when `value` is undefined but `key` is defined.

fix: variant() debug log

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/test/client.test.ts

fix: convert initial variants so experiment key is tracked correctly

---

packages/experiment-tag/src/experiment.ts

Fix Web Experimentation URL redirect preview max stack exceeded

chore: fix Web Experimentation URL redirect preview max stack exceeded

---

packages/experiment-tag/src/experiment.ts

chore: catch errors thrown from inject and log to console

---

packages/analytics-connector/src/analyticsConnector.ts

Make AnalyticsConnector getInstance backwards compatible between use in web experimentation script and feature experiment SDK

fix: Make AnalyticsConnector getInstance backwards compatible

---

packages/experiment-browser/src/integration/manager.ts
packages/experiment-browser/test/integration/manager.test.ts

fix: persistent tracking queue flush when tracker set

---

packages/experiment-tag/src/messenger.ts

Add origin check for MessageEvent that triggers visual editor initialization in Web Experimentation.

fix: add MessageEvent origin check for visual editor initialization

---

packages/experiment-browser/src/experimentClient.ts

Catch flag fetch timeout error even when the experiment client is not in debug logging mode.

fix: catch flag fetch timeout error when not in debug mode

---

packages/experiment-browser/src/factory.ts
packages/experiment-browser/src/index.ts
packages/experiment-tag/src/experiment.ts
packages/experiment-tag/test/experiment.test.ts

1. Exports `initialize` and `initializeWithAmplitudeAnalytics` directly from the SDK module. This avoids Experiment.Experiment.initializeWithAmplitudeAnalytics when installing via script.
2. Sets `window.Experiment` equal to full feature experiment SDK package in web script. This allows customers to create feature experiment SDK instances using the web experiment script (one script for both feature and web).

feat: add feature experiment support in web script

---

packages/experiment-browser/src/providers/default.ts

Catch error from getUrlParam() in DefaultUserProvider when `new URL(this.globalScope.location.href)` throws an error.

fix: Catch error in getUrlParam() in DefaultUserProvider

---

packages/experiment-browser/src/integration/manager.ts
packages/experiment-browser/test/integration/manager.test.ts

fix: fix unexposure events not deduped by integration

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/test/experiment.test.ts

Necessary migration to use web_exp_id for web experiment device_id bucketing

feat: migrate to use web_exp_id for web experiment device_id bucketing

---

packages/experiment-tag/src/experiment.ts

This fix will update the web experiment initialization logic such that antiflicker is only applied for experiments that are active on a given page.

fix: Web Experiment - only apply antiflicker for active experiments on page

---

packages/plugin-segment/src/plugin.ts
packages/plugin-segment/test/plugin.test.ts

fix: segment plugin use local initialized variable

---

packages/plugin-segment/src/plugin.ts
packages/plugin-segment/src/snippet.ts

fix: segment plugin abstract nested instance

---

packages/experiment-browser/src/experimentClient.ts

fix: wait for context before web experiment flags req

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-tag/src/experiment.ts
packages/experiment-tag/test/experiment.test.ts
packages/experiment-tag/test/util/create-flag.ts

Store flags fetched from network in session storage and re-use the flags when applying local flags before re-fetching from remote.

fix: store remote flags in session storage for reuse within session

---

packages/experiment-browser/src/util/state.ts

When a base64 string has `=` padding at the end, the base64 parse would fail.

fix: fix cookie parsing for b64 strings

---

packages/experiment-browser/src/factory.ts
packages/experiment-browser/src/integration/manager.ts
packages/experiment-tag/src/experiment.ts

* Refactor the factory functions to only init and add the plugin when a singleton instance does not already exist.
* Remove error log on integration timeout because unified script calls this function for web experiment.

fix: dont re-add plugin; remove integration timout error log

---

packages/experiment-tag/src/messenger.ts

Add nonce to new script tags for CSP. 
* Does your PR have a breaking change?: no

fix: add nonce

---

packages/experiment-tag/src/experiment.ts

Updates the control variant condition, the existence of a payload is no longer valid as we will support mutations on the control variant.
The control variant should always trigger `exposureWithDedupe()`, and then apply any variant actions as necessary.

fix: Web Experiment - Control variant condition

---

packages/experiment-tag/src/experiment.ts

Fix for control `$impression` tracking - event should be fired regardless of whether control variant actions occur.

fix: always track control impression when on active page

---

yarn.lock

SKY-8129 
update dom-mutator in yarn.lock to point to latest commit with support for `after` position mutations.
The update https://github.com/amplitude/dom-mutator/pull/9 is a copy of the fork in https://github.com/amplitude/javascript/pull/79026/ 

feat: update dom-mutator

---

.github/workflows/release.yml

The GH Action exits early if exit code 1 is outputted.
Now we ignore exit code and `experiment_plugin_updated=false` will still get output when no matches are detected.
See for fix
https://unix.stackexchange.com/questions/330660/preventing-grep-from-causing-premature-termination-of-bash-e-script

chore: ignore grep when outputting exit code 1

---

packages/experiment-tag/package.json
packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/util/cookie.ts
yarn.lock

Set analytics marketing cookie upon redirect action. This will ensure the analytics SDK has the correct campaign information about the original landing page. 

fix: set marketing cookie on landing page before redirect

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/util/patch.ts

Patch `removeChild` to address errors stemming from NextJs hydration mismatch, which attempt to remove nodes created by dom-mutator when innerHTML is set.
* Does your PR have a breaking change?: No

fix: add patch to removeChild to address hydration errors

---

packages/experiment-tag/src/util/cookie.ts

Marketing cookies should expire after session, as they are only used to pass props to analytics SDK and should not be persisted.

fix: expire marketing cookie after session

---

packages/experiment-tag/src/util/url.ts
packages/experiment-tag/test/url.test.ts

- Updated `removeQueryParams` function to handle URLs with hash fragments, allowing for the removal of query parameters in both standard and hash-based routing scenarios.
- Added comprehensive unit tests for various cases, including edge cases and hash-based routes, ensuring robust functionality.

fix: update removeQueryParams to support hash-based routing

---

packages/experiment-core/src/evaluation/evaluation.ts
packages/experiment-core/src/evaluation/select.ts

My earlier fix (#143 ) was not complete. This removes remaining instances of early returns when a property value evaluates to false. This allows to correctly evaluate comparisons like `0==0` or `0<1` or `false=false`.
However, we need to make sure that this isn't expected behavior for some use cases. Atm, comparing the `(none)` value that you can select in the conditions builder to number value `0` or boolean value `false` would evaluate to `true` which changes with this PR. 

fix: do not treat falsy values like 0 and false as undefined
