packages/browser/src/experimentClient.ts
packages/browser/test/client.test.ts

* more tests for experiment client
* fixes based on tests

fix: add additional client tests and fixes

---

packages/browser/src/integration/amplitude.ts

fix: type issue with global amp instance

---

packages/browser/src/integration/amplitude.ts

* Fix ts build issue #17 
* Fix unset
* Does your PR have a breaking change?:   NO

fix: fix unset user property

---

packages/browser/src/integration/amplitude.ts

fix: remove _logEvent from instance type

---

packages/browser/src/integration/connector.ts

feat: update analytics connector to use exposure v2

---

packages/analyticsConnector/package.json
packages/analyticsConnector/src/analyticsConnector.ts
packages/browser/package.json

fix: support script tag installs for analytics connector

---

packages/browser/src/config.ts
packages/browser/src/experimentClient.ts
packages/browser/src/transport/http.ts
packages/browser/src/types/transport.ts
packages/browser/test/client.test.ts

* Add ability to configure http client interface in config.

feat: add http client config

---

packages/analyticsConnector/src/identityStore.ts

fix: dont use includes to support IE11

---

packages/analyticsConnector/src/identityStore.ts

Polyfill object entries to support ie11
* Does your PR have a breaking change?:  NO

fix: polyfill object entries for ie11

---

packages/browser/src/experimentClient.ts

increase integration timeout to 10 seconds
* Does your PR have a breaking change?:   NO

fix: increase timeout for experiment integration to 10 seconds

---

packages/browser/src/types/user.ts

* add groups and group properties on skylab user

feat: support groups and group properties on skylab user

---

packages/analyticsConnector/src/identityStore.ts
packages/analyticsConnector/src/util/equals.ts
packages/analyticsConnector/test/equals.test.ts

Fix bug comparing null in identity store. #41 

fix: move isEqual to util, add null check

---

packages/analyticsConnector/src/util/global.ts

fix: #44 ReferenceError: global is not defined

---

package.json
packages/analyticsConnector/rollup.config.js
packages/browser/rollup.config.js
yarn.lock

Adds bundle size summary and composition report to rollup tasks.
Example output:
```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    96.071 KB
original size:  111.111 KB
code reduction: 13.54 %
module count:   26
/node_modules/@amplitude/ua-parser-js/src/ua-parser.js
██████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 36.97 % (35.522 KB)
/src/experimentClient.ts
██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 20.86 % (20.043 KB)
/node_modules/@amplitude/analytics-connector/dist/analyticsConnector.esm.js
████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 9.25 % (8.891 KB)
/Users/username/workspace/experiment-js-client/node_modules/tslib/tslib.es6.js
██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 4.41 % (4.239 KB) …
```

build: adds bundle size analyzer plugin to rollup

---

examples/html-app/amplitude-integration/README.md
examples/html-app/amplitude-integration/index.html
examples/html-app/amplitude-integration/package.json
examples/html-app/basic/README.md
examples/html-app/basic/index.html
examples/html-app/basic/package.json

New html script tag examples for experiment SDKs

docs: experiment examples - html

---

.github/workflows/lint.yml
.github/workflows/release.yml

chore: update actions

---

packages/experiment-browser/src/factory.ts
packages/experiment-browser/test/factory.test.ts

fix: intialize with custom user provider

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/util/convert.ts
packages/experiment-browser/test/convert.test.ts

Add support for groups and group properties w/ client-side local evaluation.

fix: add support for groups with client-side local eval

---

packages/experiment-browser/src/experimentClient.ts

Handle localStorage errors from iframe

fix: Handle localStorage errors from iframe

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/test/client.test.ts
packages/experiment-core/src/api/evaluation-api.ts
packages/experiment-core/src/evaluation/error.ts
packages/experiment-core/src/index.ts

Improve remote evaluation fetch retry logic

fix: Improve remote evaluation fetch retry logic

---

packages/experiment-tag/src/messenger.ts

Fix visual editor regex for matching message origins. 

fix: fix regex for overlay msg

---

packages/experiment-tag/example/build_example.js
packages/experiment-tag/package.json
packages/experiment-tag/rollup.config.js
packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/messenger.ts
packages/experiment-tag/test/experiment.test.ts

Update web experimentation script tag with visual editor support

chore: update web experimentation script tag with visual editor support

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/types/client.ts
packages/experiment-core/src/api/evaluation-api.ts
packages/experiment-core/src/index.ts
yarn.lock

feat: add options evaluation api in experiment-core

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/util.ts

Fix recursive application of element change

chore: fix recursive application of element change

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/inject-utils.ts

fix: add inject support to experiment-tag

---

.gitignore
packages/analytics-connector/package.json
packages/analytics-connector/src/eventBridge.ts
packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/factory.ts
packages/experiment-browser/src/util/convert.ts
packages/experiment-browser/test/convert.test.ts
packages/experiment-core/src/index.ts
packages/experiment-core/src/util/global.ts
packages/experiment-tag/package.json
packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/messenger.ts
packages/experiment-tag/src/util.ts
packages/experiment-tag/test/experiment.test.ts
packages/experiment-tag/test/util.test.ts

Add page targeting functionality for web experimentation

feat: Page targeting for Web Experimentation

---

packages/experiment-tag/src/experiment.ts

Replace eval with an inline inject

chore: use inline inject instead of eval

---

packages/experiment-tag/src/script.ts

Anti-flicker script is:
```
<script>
// Set a timeout in milliseconds for the anti-flicker.
var timeout = 1000;
var id = "amp-exp-css";
if (!document.getElementById(id)) {
var s = document.createElement("style");
s.id = id;
s.innerText = "* { visibility: hidden !important; background-image: none !important; }";
document.head.appendChild(s);
window.setTimeout(function () {s.remove()}, timeout);
}
</script>
```

chore: update experiment script to support async

---

packages/experiment-browser/src/integration/default.ts
packages/experiment-browser/src/storage/local-storage.ts
packages/experiment-browser/src/storage/session-storage.ts
packages/experiment-browser/src/types/user.ts
packages/experiment-browser/test/defaultUserProvider.test.ts
packages/experiment-core/src/evaluation/evaluation.ts
packages/experiment-tag/src/util.ts
packages/experiment-tag/test/util.test.ts

Added URL search parameter targeting. 
Fixed multiple search parameter with same key doesn't get passed to redirect. 
Added global scope to lots of places.

feat: add url param targeting

---

packages/experiment-tag/src/experiment.ts

chore: set Web Experiment client as window.webExperiment

---

packages/experiment-browser/src/integration/manager.ts

fix: add poller back to persistent tracking queue

---

packages/experiment-browser/src/experimentClient.ts
packages/experiment-browser/src/transport/http.ts
packages/experiment-core/src/evaluation/error.ts
packages/experiment-core/src/index.ts

Catch variant/flag fetch timeout error and use debug log

fix: catch variant/flag fetch timeout error and use debug log

---

packages/experiment-tag/src/messenger.ts

Caches messenger errors that can throw. 

fix: catch messenger error

---

packages/analytics-connector/package.json

chore(analytics-connector): remove experiment-core dependency

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/test/experiment.test.ts

fix: Web experiment action deduplication

---

packages/experiment-tag/package.json
yarn.lock

fix: use main branch patch of dm

---

packages/experiment-tag/package.json
packages/experiment-tag/rollup.config.js
packages/experiment-tag/src/index.ts

fix: update experiment tag packaging; export types

---

packages/experiment-browser/src/integration/manager.ts

fix: catch integration tracker error in PersistentTrackingQueue

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/test/experiment.test.ts

fix: track control impressions on targeted pages

---

packages/experiment-tag/src/experiment.ts

Fix control variant impression scoping. If control variant actions are not empty, `$impression` should only be fired if actions are scoped to the page.
`shouldTrackExposure` metadata is no longer required after pageObject support.

fix: scoping for control impression event actions, remove shouldTrackExposure check

---

packages/experiment-tag/package.json
yarn.lock

update dom-mutator hash in package.json to be more like versioning (will trigger new build)
This is related to https://github.com/amplitude/experiment-js-client/pull/199 which updates dom-mutator for multiple fixes and new position support.

feat: update dom-mutator hash in package.json to be more like versioning

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/util/messenger.ts

feat: Support visual editor mode for multi-page apps

---

packages/experiment-tag/src/experiment.ts
packages/experiment-tag/src/types.ts
packages/experiment-tag/src/util/messenger.ts
packages/experiment-tag/src/util/storage.ts

Update `experiment-tag` to use `storage.ts` utils for get/set/delete operations for localStorage and sessionStorage.
* Does your PR have a breaking change?: No

chore: refactor package to use centralized storage.ts util
